apiVersion: apps/v1
kind: Deployment
metadata:
  name: twik-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twik-home
  template:
    metadata:
      labels:
        app: twik-home
    spec:
      volumes:
        # Create the shared files volume to be used in both pods
        - name: shared-files
          emptyDir: {}

        # Add the ConfigMap we declared above as a volume for the pod
        - name: nginx-config-volume
          configMap:
            name: nginx-config

      initContainers:
        - name: laraavel-app
          image: alonronin/laravel-app:latest
          securityContext:
            runAsUser: 0
          command:
            - "/bin/bash"
            - "-c"
            - "cp -r /app/. /var/www/html"
          volumeMounts:
            - name: shared-files
              mountPath: /var/www/html

      containers:
        # Our PHP-FPM application
        - image: alonronin/php-fpm:latest
          name: php-fpm
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: shared-files
              mountPath: /var/www/html

        # Our nginx container, which uses the configuration declared above,
        # along with the files shared with the PHP-FPM app.
        - image: nginx
          name: nginx
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: shared-files
              mountPath: /var/www/html
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
